<?php
include 'conexaoMysql.php';

$$EMPRESA_PEDIDO = $_POST['EMPRESA_PEDIDO'];
$COD_PED_PEDIDO = $_POST['COD_PED_PEDIDO'];
$NOME_CLI_FOR_PEDIDO = $_POST['NOME_CLI_FOR_PEDIDO'];
$DT_EMISSAO_PEDIDO = $_POST['DT_EMISSAO_PEDIDO'];
$COD_CLI_PEDIDO = $_POST['COD_CLI_PEDIDO'];
$TIPO_TRANSP_PEDIDO = $_POST['TIPO_TRANSP_PEDIDO'];
$USU_INCLUI_PEDIDO = $_POST['USU_INCLUI_PEDIDO'];  

$SITUACAO = "EM SEPARACAO";
$SEPARADOR = $_POST['SEPARADOR'];



date_default_timezone_set('America/Araguaina'); //HORARIO NESSA ZONA É -1 DE BRASILIA, SE HOUVER HORARIO DE VERAO NOVAMENTE RETORNAR PARA ZONA DE SAO_PAULO
$DATA = date('d-m-Y h:i:sa');

$sql = "INSERT INTO logistica_separacao (SEPARADOR,COD_PED,NOME_CLI_FOR,SITUACAO,TIPO_TRANSP,COD_CLI,DATA,VENDEDOR,ASS_CANHOTO,ENVIADO_SEPARACAO,PAINEL,COMPRADOR)
VALUES ('$SEPARADOR','$COD_PED_PEDIDO','$NOME_CLI_FOR_PEDIDO','$SITUACAO','$TIPO_TRANSP_PEDIDO','$COD_CLI_PEDIDO','$DATA','$USU_INCLUI_PEDIDO','','','','')";
if (mysqli_query($conn, $sql)) {
    echo "Registrado com sucesso!";
  } else {
    echo "Error: " . $sql . "<br>" . mysqli_error($conn);
  }


  
$queryb = "SELECT FIRST 1 ITEMS_ORCAMENTO.COD_ORC, ITEMS_ORCAMENTO.COD_PROD,PRODUTOS.LOCAL_ALMOX,
ITEMS_ORCAMENTO.QTDE_PED, PRODUTOS.NOME_PROD, PRODUTOS.COD_PROD,ITEMS_ORCAMENTO.OBS, ITEMS_ORCAMENTO.COD_EMP
FROM ITEMS_ORCAMENTO  
INNER JOIN PRODUTOS ON (PRODUTOS.COD_PROD = ITEMS_ORCAMENTO.COD_PROD)
WHERE COD_ORC = $COD_PED_PEDIDO AND ITEMS_ORCAMENTO.COD_EMP = $EMPRESA_PEDIDO  AND PRODUTOS.LOCAL_ALMOX LIKE 'AZUL'";

$data2 = $connect->query($queryb);

foreach($data2 as $row)
{    
  
 
  //CONFERE SE O PEDIDO JÁ FOI SEPARADOR, SE NAO ADICIONA NOVAMENTE
  $sql = "SELECT COD_PED FROM logistica_separacao_fragmentada_azul WHERE COD_PED = '$COD_PED_PEDIDO'";
  $resultado = mysqli_query($conn, $sql);
   if(mysqli_num_rows($resultado) > 0)
   {
  
     echo"<b>JÁ ESTA NA LISTA PARA SEPARAÇÃO AZUL</b><br>";
 
   }
   else
   { // AQUI É ADCIONADO NOVAMENTE O PEDIDO PARA SEPARAR
    $LOCAL_ALMOX = $row['LOCAL_ALMOX'];
    $SITUACAO = "ENVIADO AUTO.";
    $POSICAO = 0;
    $TIPO = "PEDIDO";
    $sql = "INSERT INTO logistica_separacao_fragmentada_azul (COD_PED,NOME_CLI_FOR,USU_INCLUI,TIPO_TRANSP,LOCAL_ALMOX,SITUACAO,POSICAO,DT_EMISSAO,EMPRESA,TIPO_SEPARACAO) 
    VALUES ('$COD_PED_PEDIDO','$NOME_CLI_FOR_PEDIDO','$USU_INCLUI_PEDIDO','$TIPO_TRANSP_PEDIDO','$LOCAL_ALMOX','$SITUACAO','$POSICAO','$DT_EMISSAO_PEDIDO','$EMPRESA_PEDIDO','$TIPO')";
    $resultado = mysqli_query($conn, $sql);
   
    
    echo"<b>ENVIADO PARA AZUL</b><br>";
   

   }
 }